# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{machine}}_carn
  pre_tasks:
  - fail: msg="This playbook only runnable on 'app' machines"
    when: "'app' not in machine"
  sudo: True
  vars:
    not_prod: false
    secure_dir: "../../../edx-secret/ansible"
    local_dir: "../../../edx-secret/ansible/local"
    nginx_template_dir: "../../../edx-secret/ansible/local/nginx/templates"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_carnegie_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
  roles:
    - common
    - supervisor
    - {'role': 'nginx', 'nginx_conf': true}
    - {'role': 'edxapp', 'openid_workaround': true, 'template_subdir': 'carnegie'}
    # run this role last
    # - in_production
