
# set up the fireball transport
#- hosts: ~tag_Name_app(10|20)_cme
#  gather_facts: no
#  connection: ssh # or paramiko
#  sudo: yes
#  tasks:
#      - apt: pkg=gcc state=present
#      - apt: pkg=libzmq-dev,python-zmq state=present
#      - action: fireball

# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{machine}}_cme
  pre_tasks:
  - fail: msg="This playbook only runnable on 'app' machines"
    when: "'app' not in machine"
  sudo: True
  vars:
    not_prod: true
    secure_dir: "../../../edx-secret/ansible"
    local_dir: "../../../edx-secret/ansible/local"
    nginx_template_dir: "../../../edx-secret/ansible/local/nginx/templates"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_cme_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_conf: true
      nginx_sites:
      - lms
      - cms
      - lms-preview
      nginx_default_sites:
      - lms
    - {'role': 'edxapp', 'openid_workaround': true, 'template_subdir': 'cme'}
    # run this role last
    # - in_production
