# this gets all running prod webservers
#- hosts: tag_environment_prod:&tag_function_xqueue
# or we can get subsets of them by name
- hosts: ~tag_Name_xqueue10_prod
#- hosts: security_group_edx-prod-EdxappServerSecurityGroup-NSKCQTMZIPQB
  sudo: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../configuration-secure/ansible/local'
  vars_files:
    - "{{ secure_dir }}/vars/xqueue_prod_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/datadog_prod.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - xqueue
      - basic-auth
    - xqueue
    - datadog
    #- splunkforwarder
